### PR TITLE
feat: support angular 15 peer dependencies

### PR DESCRIPTION
**Pull request by lincolnthree**
Currently, this we locked into using solely Angular 14 because of the current peer dependencies. It would be nice if we could also use it for Angular 15. Thanks! Love this library.

### CODE REVIEW

**Comment by Shamshiel** [comment]
Same for a project that I have to maintain. We can't upgrade to Angular v15 because of this package.

**Comment by doughlass** [comment]
@lincolnthree @Shamshiel I'll be forking this and publishing a new library today using Angular 15

**Comment by doughlass** [comment]
@lincolnthree @Shamshiel https://www.npmjs.com/package/@doughlass/ng-inline-svg

**Comment by lincolnthree** [comment]
@doughlass Nice! Thank you. I had been using a github fork and installing from there: https://github.com/lincolnthree/ng-inline-svg/tree/dist

**Comment by lincolnthree** [comment]
@siandreev Ping. Just in case you aren't getting PR notifications. Your lib is starting to get forked because of this! Easy PR for you is waiting and ready :)

**Review by siandreev — APPROVED** [review]

**Comment by siandreev** [comment]
> @siandreev Ping. Just in case you aren't getting PR notifications. Your lib is starting to get forked because of this! Easy PR for you is waiting and ready :)

Thx for the ping, library updated 👍

**Pull request merged**
